# Generated by Django 5.2.14 on 2026-05-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_host', models.CharField(max_length=255)),
                ('old_port', models.PositiveIntegerField(default=993)),
                ('old_username', models.CharField(max_length=255)),
                ('old_use_ssl', models.BooleanField(default=True)),
                ('new_host', models.CharField(max_length=255)),
                ('new_port', models.PositiveIntegerField(default=993)),
                ('new_username', models.CharField(max_length=255)),
                ('new_use_ssl', models.BooleanField(default=True)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('backup', 'Backup'), ('transfer', 'Transfer'), ('verify', 'Verify'), ('cleanup', 'Cleanup')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('log_path', models.CharField(blank=True, max_length=500)),
                ('migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_runs', to='migrator.migration')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('total_old', models.PositiveIntegerField(default=0)),
                ('total_new', models.PositiveIntegerField(default=0)),
                ('missing_total', models.PositiveIntegerField(default=0)),
                ('folders_json', models.JSONField(default=dict)),
                ('migration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='migrator.migration')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=500)),
                ('message_id', models.CharField(max_length=500)),
                ('backed_up', models.BooleanField(default=False)),
                ('transferred', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField(default=0)),
                ('migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='migrator.migration')),
            ],
            options={
                'indexes': [models.Index(fields=['migration', 'folder'], name='migrator_me_migrati_990fd2_idx'), models.Index(fields=['migration', 'message_id'], name='migrator_me_migrati_41bc24_idx')],
                'unique_together': {('migration', 'folder', 'message_id')},
            },
        ),
        migrations.CreateModel(
            name='FolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_folder', models.CharField(max_length=500)),
                ('new_folder', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('map', 'Map to existing folder'), ('create', 'Create on new server'), ('skip', 'Skip')], default='map', max_length=10)),
                ('pairing_reason', models.CharField(blank=True, max_length=20)),
                ('special_use', models.CharField(blank=True, max_length=20)),
                ('migration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_mappings', to='migrator.migration')),
            ],
            options={
                'unique_together': {('migration', 'old_folder')},
            },
        ),
    ]
