# Generated by Django 5.2.14 on 2026-05-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecord',
            name='flags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='internaldate',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='raw_bytes',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='messagerecord',
            name='source_uid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
