# Generated by Django 5.2.14 on 2026-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0005_backfill_migration_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='new_password_enc',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='migration',
            name='old_password_enc',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
