# Generated by Django 5.2.14 on 2026-07-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('visit', 'Page visit'), ('signup', 'Account signup')], default='visit', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='migrator_ac_created_2aec12_idx'), models.Index(fields=['seen'], name='migrator_ac_seen_830fcc_idx'), models.Index(fields=['kind'], name='migrator_ac_kind_4d9023_idx')],
            },
        ),
    ]
