# Generated by Django 5.2.14 on 2026-07-24 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0008_accessevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessevent',
            options={'ordering': ['-last_seen', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='accessevent',
            name='migrator_ac_created_2aec12_idx',
        ),
        migrations.AddField(
            model_name='accessevent',
            name='hits',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['-last_seen'], name='migrator_ac_last_se_aca197_idx'),
        ),
    ]
