# Generated by Django 5.2.14 on 2026-08-03 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0009_alter_accessevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('password_enc', models.BinaryField(blank=True, default=b'')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('folders_listed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BackupFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('delimiter', models.CharField(default='/', max_length=4)),
                ('special_use', models.CharField(blank=True, max_length=20)),
                ('selected', models.BooleanField(default=True)),
                ('server_count', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='migrator.backupjob')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('job', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BackupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=500)),
                ('message_id', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_addr', models.CharField(blank=True, max_length=320)),
                ('date_header', models.CharField(blank=True, max_length=120)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('size', models.PositiveIntegerField(default=0)),
                ('raw_bytes', models.BinaryField(blank=True, default=b'')),
                ('flags', models.TextField(blank=True)),
                ('internaldate', models.CharField(blank=True, max_length=64)),
                ('source_uid', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='migrator.backupjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'folder'], name='migrator_ba_job_id_4a386b_idx')],
                'unique_together': {('job', 'folder', 'message_id')},
            },
        ),
    ]
