# Generated by Django 5.2.14 on 2026-08-03 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0010_backupjob_backupfolder_backupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='backup-scheduler', max_length=50, unique=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='backupjob',
            name='last_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='schedule',
            field=models.CharField(choices=[('off', 'Off — run manually'), ('hourly', 'Every hour'), ('6h', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every week')], default='off', max_length=10),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='schedule_hour',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='schedule_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='schedule_weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
