# Generated by Django 5.2.14 on 2026-08-03 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0011_schedulerheartbeat_backupjob_last_scheduled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('password_enc', models.BinaryField(blank=True, default=b'')),
                ('source_kind', models.CharField(choices=[('upload', 'Uploaded archive'), ('backup', 'Existing backup in this app')], default='upload', max_length=10)),
                ('archive_name', models.CharField(blank=True, max_length=255)),
                ('archive_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='migrator.backupjob')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RestoreFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_folder', models.CharField(max_length=500)),
                ('dest_folder', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('map', 'Import into existing folder'), ('create', 'Create on destination'), ('skip', 'Skip')], default='map', max_length=10)),
                ('pairing_reason', models.CharField(blank=True, max_length=20)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='migrator.restorejob')),
            ],
            options={
                'ordering': ['source_folder'],
                'unique_together': {('job', 'source_folder')},
            },
        ),
        migrations.CreateModel(
            name='RestoreMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=500)),
                ('message_id', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_addr', models.CharField(blank=True, max_length=320)),
                ('date_header', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('raw_bytes', models.BinaryField(blank=True, default=b'')),
                ('flags', models.TextField(blank=True)),
                ('internaldate', models.CharField(blank=True, max_length=64)),
                ('imported', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='migrator.restorejob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'folder'], name='migrator_re_job_id_e424fa_idx')],
                'unique_together': {('job', 'folder', 'message_id')},
            },
        ),
    ]
