# Generated by Django 5.2.14 on 2026-08-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0012_restorejob_restorefolder_restoremessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='schedule',
            field=models.CharField(choices=[('off', 'Off — run manually'), ('hourly', 'Every hour'), ('6h', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every week'), ('5min', 'Every 5 minutes (testing only)')], default='off', max_length=10),
        ),
    ]
