# Generated by Django 5.2.14 on 2026-08-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0013_alter_backupjob_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorefolder',
            name='source_delimiter',
            field=models.CharField(default='/', max_length=4),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='schedule',
            field=models.CharField(choices=[('off', 'Off — run manually'), ('hourly', 'Every hour'), ('6h', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every week')], default='off', max_length=10),
        ),
    ]
