# Generated by Django 5.2.14 on 2026-08-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0014_restorefolder_source_delimiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='interrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='resumed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='worker',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='phaserun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='phaserun',
            name='interrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phaserun',
            name='resumed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phaserun',
            name='worker',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='interrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='resumed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restorejob',
            name='worker',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
