# Generated by Django 5.2.14 on 2026-08-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0015_backupjob_heartbeat_at_backupjob_interrupted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='schedule',
            field=models.CharField(choices=[('off', 'Off — run manually'), ('30m', 'Every 30 minutes'), ('hourly', 'Every hour'), ('6h', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every week')], default='off', max_length=10),
        ),
    ]
