# Generated by Django 5.2.14 on 2026-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0016_alter_backupjob_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='schedule',
            field=models.CharField(choices=[('off', 'Off — run manually'), ('10m', 'Every 10 minutes'), ('30m', 'Every 30 minutes'), ('hourly', 'Every hour'), ('6h', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every week')], default='off', max_length=10),
        ),
    ]
