# Generated by Django 5.2.14 on 2026-09-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0018_alter_backupjob_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermapping',
            name='old_message_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
