# Generated by Django 5.2.14 on 2026-09-01 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrator', '0019_foldermapping_old_message_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password_enc', models.BinaryField(blank=True, default=b'')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['host', 'username'],
                'unique_together': {('owner', 'host', 'username')},
            },
        ),
    ]
